### ISSUE TITLE
more extensive task sheduling options

### ISSUE THREAD

**Issue by cryptolovi** [hashtopolis/server#462] opened 2018-09-03 15:27 UTC
* cyclic execution on running tasks with the same priority when no higher priority tasks exists (notes: disable benchmarking again when an agent returns to a task that it already has processed a chunk for)
* round robin on multiple same high priority tasks (available after each task has been benchmarked) to spread equal time slices on the tasks.

**Comment by zyronix** [comment] 2023-06-15 12:05
> cyclic execution on running tasks with the same priority when no higher priority tasks exists (notes: disable benchmarking again when an agent returns to a task that it already has processed a chunk for)
Partially implement with #879 and #843

> round robin on multiple same high priority tasks (available after each task has been benchmarked) to spread equal time slices on the tasks.
Duplicate of #843

**Closed by zyronix** 2023-06-15 12:05 UTC
Labels: new feature
